version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: daily
    groups:
      version:
        applies-to: version-updates
        update-types:
          - patch
          - minor
